import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { fetchAllProducts } from "../redux/action";
import styles from "../styles/Home.module.css";
import { wrapper } from "../redux/store";
import { useEffect } from "react";

export const getServerSideProps = wrapper.getServerSideProps(
  async ({ store }) => {
    const dispatch = store.dispatch;
    await dispatch(await fetchAllProducts());
  }
);
 
const Home = () => {
  useEffect(()=>{
    dispatch(fetchAllProducts())
     console.log(Data,'hey');
  },[])
  const dispatch = useDispatch();
  const Data = useSelector((state) => state.userReducer.products);





  return (
    <div className={styles.container}>
      <Head>
        <title>Next redux crud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {Data.map((dat) => (
          <>
           <p key={dat.id}>{dat.id}</p>
          <p >{dat.title}</p>
         
          <img src={dat.image}/>
          </>
        ))}
        
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Simple Next-redux crud
        </a>
      </footer>
    </div>
  );
};

export default Home;
